---
title: '`ggmatplot`: An R package for data visualization on wide-format data'
tags:
- R
- grammar of graphics
- ggplot2
- data visualisation
authors:
  - name: Xuan Liang
    orcid: 0000-0002-0792-3751
    affiliation: 1
  - name: Francis K. C. Hui
    orcid: 0000-0003-0765-3533
    affiliation: 1
  - name: Dilinie Seimon
    orcid: 0000-0003-4431-6077
    affiliation: 2
  - name: Emi Tanaka
    orcid: 0000-0002-1455-259X
    affiliation: 2
affiliations:
  - name: The Australian National University
    index: 1
  - name: Monash University
    index: 2
citation_author: Liang et. al.
date: "`r Sys.Date()`"
year: 2022
bibliography: paper.bib
output: rticles::joss_article
csl: apa.csl
journal: JOSS
---



# Summary

The layered grammar of graphics [@Wickham2010-kt], implemented as the `ggplot2` package [@Wickham2016] in the statistical language R [@rstats], is a powerful tool to create versatile statistical graphics. This graphical system, however, requires input data to be organised in a manner that a data column is mapped to an aesthetic element (e.g. x-coordinate, y-coordinate, color, size), which create friction in constructing plots with an aesthetic element that span multiple columns in the data by requiring users to re-organise the data.  

The `ggmatplot`, built upon `ggplot2`, is an R-package that allows quick plotting across the columns of matrics or data with the result returned as a `ggplot` object. The package is inspired by the function `matplot()` in the core R `graphics` system, thus `ggmatplot` can be considered as a `ggplot` version of `matplot` with the benefits of customising the plots as any other `ggplot` objects via `ggplot2` functions.


# Statement of need

Data can be tidied in a rectangular form where each row represents an observational unit, each column represents a variable, and each cell represents a value [@Wickham2014-gy]. What constitutes a variable, hence a column, in a tidy data are dependent upon interpretation.

---

The increased use of a tidy approach in structuring datasets results in wrangling datasets into wide format: with variables as columns and observations as rows(https://vita.had.co.nz/papers/tidy-data.html). While this introduces a more meaningful mapping of the data into its structure, the grammar of graphics requires wide format data to be wrangled back into long format for visualizing. This can be quite cumbersome when creating simple plots, and converting a tidy data frame back to a long format with multiple variables stacked upon each other can also be considered counter-intuitive.

Therefore, the motivation for `ggmatplot` is to provide a solution that allows `ggplot2` to handle wide format data. Although `ggmatplot` doesn't provide the same flexibility as `ggplot2`, it can be used as a workaround for having to wrangle wide format data into long format and creating simple plots using `ggplot2`.

# Examples



# Acknowledgements



# References
